version: '3'

services:
    zeppelin:
        hostname: zeppelin
        container_name: zeppelin
        image: apache/zeppelin:0.8.1
        depends_on:
            - neo4j
        ports:
            - 8080:8080
        volumes:
        - ./zeppelin/notebook:/zeppelin/notebook
        - ./zeppelin/conf:/zeppelin/conf
        - ./zeppelin/data:/zeppelin/spark-warehouse
    neo4j:
        image: neo4j:3.5
        hostname: neo4j
        container_name: neo4j
        ports:
            - 7474:7474
            - 7687:7687
        environment:
            - NEO4J_AUTH=neo4j/zeppelin